enableImmutableInstalls: false

nodeLinker: node-modules

npmRegistryServer: "https://registry.npmjs.org/"

packageExtensions:
  eslint-config-next@*:
    peerDependencies:
      next: "*"
  react-server-dom-webpack@*:
    peerDependencies:
      react: "*"
  kbar@*:
    peerDependencies:
      react: "*"
      react-dom: "*"
  react-virtual@*:
    peerDependencies:
      react: "*"
  compression-webpack-plugin@*:
    peerDependencies:
      webpack: "^5.0.0"

yarnPath: .yarn/releases/yarn-4.9.1.cjs
