nodeLinker: node-modules
enableImmutableInstalls: false
npmRegistryServer: "https://registry.npmjs.org/"
packageExtensions:
  react-server-dom-webpack@*:
    peerDependencies:
      react: "*"
  eslint-config-next@*:
    peerDependencies:
      next: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.6.1.cjs
