enableImmutableInstalls: false

nodeLinker: node-modules

npmRegistryServer: "https://registry.npmjs.org/"

packageExtensions:
  eslint-config-next@*:
    peerDependencies:
      next: "*"
  react-server-dom-webpack@*:
    peerDependencies:
      react: "*"

yarnPath: .yarn/releases/yarn-4.9.1.cjs
